### ISSUE TITLE
Fatal error has occurred

### ISSUE THREAD

**Issue by n0brainer** [jamf/HealthCheckUtility#10]
Running against a 9.97.1488392992 JSS - and every time I go to sign in, Fatal Error window pops up...
<img width="427" alt="screen shot 2017-03-23 at 8 04 41 am" src="https://cloud.githubusercontent.com/assets/2116991/24248931/67741608-0f9f-11e7-82b3-43ae500d6702.png">

Java JDK 8 build 121.

**Comment by kktspecial** [comment]
hey did you ever get this solved?

**Comment by andysenn** [comment]
@n0brainer @kktspecial - I have a change in the works for this. I will try to get it pushed through shortly. Thank you for your patience and feedback!

**Comment by andysenn** [comment]
@n0brainer @kktspecial - So this has actually turned into a bit of a nest. I will continue to work on it, but the turnaround time won't be short, unfortunately. I think that there are some major architectural decisions that need to be made. I will try to keep you posted.

**Comment by kktspecial** [comment]
hey @andysenn, thanks for your responses, btw. no pressure on this, i just think it's such a nifty tool and has helped me out lots in the past. :) good luck!

**Comment by Python-venkat** [comment]
I am first time user of this tool...very eager to see the report this tool will give 

<img width="509" alt="screen shot 2017-08-03 at 3 02 29 pm" src="https://user-images.githubusercontent.com/29455734/28915688-8b5657ee-785d-11e7-9f11-3aa70ca2469a.png">

**Comment by seabash** [comment]
Just confirming issue persists and regressing on OSX 10.11 El Cap with java version "1.8.0_162"
> A fatal error has occurred.
> java.lang.ArrayIndexOutOfBoundsException: 1

Different accounts see the error sooner than others, e.g. my full-privileged `jssadmin` account fails within 2-3 seconds.  Whereas my LDAP-based account (w/ _slightly_ less privs) does not error out until ~16 seconds, and the JSS Health Check status (in background) shows "Loading results...", though it does not proceed further.

**Comment by seabash** [comment]
This is error from trying to run this headless...
```
https://MyJamfProURL/JSSResource/jssuser
Performing Health Check, Please Wait...
Getting the JSS Summary
https://MyJamfProURL/JSSResource/jssuser
https://MyJamfProURL/JSSResource/jssuser
[main] ERROR com.jamfsoftware.jss.healthcheck.JSSConnectionTest - 
java.lang.NumberFormatException: multiple points
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1914)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at com.jamfsoftware.jss.healthcheck.JSSConnectionTest.getJSSVersion(JSSConnectionTest.java:95)
	at com.jamfsoftware.jss.healthcheck.HealthCheck.<init>(HealthCheck.java:98)
	at com.jamfsoftware.jss.healthcheck.ui.UserPromptHeadless.<init>(UserPromptHeadless.java:102)
	at com.jamfsoftware.jss.healthcheck.HealthCheckUtility.startUI(HealthCheckUtility.java:123)
	at com.jamfsoftware.jss.healthcheck.HealthCheckUtility.start(HealthCheckUtility.java:85)
	at com.jamfsoftware.jss.healthcheck.HealthCheckUtility.main(HealthCheckUtility.java:171)
https://MyJamfProURL/summary.html?2=on&3=off&4=on&6=on&5=on&9=on&7=on&313=on&24=on&350=on&22=on&26=on&23=on&24=on&25=on&28=on&27=on&312=on&53=on&54=on&54=on&255=on&24=on&51=on&65=on&80=on&136=on&135=on&133=on&134=on&137=on&221=on&166=on&72=on&141=on&124=on&125=on&158=on&252=on&163=on&310=on&381=on&90=on&91=on&92=on&96=on&95=on&94=on&93=on&74=on&75=on&76=on&82=on&81=on&122=on&118=on&119=on&73=on&117=on&123=on&83=on&11=on&77=on&171=on&128=on&86=on&131=on&314=on&169=on&87=on&41=on&42=on&43=on&360=on&44=on&45=on&tableRowCounts=on&tableSize=on&Action=Create&username=MyUSERpassword=MyPASSWORD
https://MyJamfProURL/JSSResource/computers
https://MyJamfProURL/JSSResource/mobiledevices
https://MyJamfProURL/JSSResource/users
Running System and Database Checks
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at com.jamfsoftware.jss.healthcheck.JSSSummary.getOperatingSystem(JSSSummary.java:185)
	at com.jamfsoftware.jss.healthcheck.HealthCheck.SystemChecks(HealthCheck.java:138)
	at com.jamfsoftware.jss.healthcheck.HealthCheck.<init>(HealthCheck.java:106)
	at com.jamfsoftware.jss.healthcheck.ui.UserPromptHeadless.<init>(UserPromptHeadless.java:102)
	at com.jamfsoftware.jss.healthcheck.HealthCheckUtility.startUI(HealthCheckUtility.java:123)
	at com.jamfsoftware.jss.healthcheck.HealthCheckUtility.start(HealthCheckUtility.java:85)
	at com.jamfsoftware.jss.healthcheck.HealthCheckUtility.main(HealthCheckUtility.java:171)
```

**Comment by cgardini99** [comment]
Any News on this?
